### ISSUE TITLE
build error because of missing UIKit.h in NSValue+JNWAdditions.h

### ISSUE THREAD

**Issue by mrmign** [jwilling/JNWSpringAnimation#9]
CGRectValue  CGSizeValue CGPointValue are defined in UIKit, CGRect CGSize CGPoint ..are defined in CG, `UIKit` should be imported here.

**Comment by jwilling** [comment]
Thank you for your report. Usually these files are included in a source file that already imports the relevant UI framework, whether it be UIKit or Cocoa. I agree that it should probably import the correct framework, but in the meantime please import UIKit in the same file that you import JNWSpringAnimation.

**Comment by siddharthsuneel** [comment]
I am still having the above mentioned issue
Please suggest me how to get rid of that problem

**Comment by jwilling** [comment]
I have fixed the issue.
